---

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:

- name: archivematica
  type: git
  source:
    uri: "https://github.com/artefactual-labs/am"
    branch: "dev/pipeline-stable-1.7.x"

- name: slack-notification
  type: slack-notification
  source:
    url: ((slack_webhook))

jobs:

- name: start-testing
  plan:
  - get: archivematica
    params:
      submodules: none
      depth: 1
  - put: slack-notification
    params:
      channel: "@sevein"
      username: "qubot"
      icon_emoji: ":artefactual:"
      text: |
        The build has started. Check it out at:
        https://ci.archivematica.org/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME

- name: acceptance-tests-upgrade-pkg-centos-7
  interruptible: true
  serial: true
  plan:
  - get: archivematica
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: archivematica/ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: centos-7-x64
      SIZE: s-2vcpu-4gb
  - task: create-droplet-from-snapshot
    file: archivematica/ci/acceptance-tests/create-droplet-from-snapshot.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-upgrade-pkg-centos-7"
      SNAPSHOT_NAME: "am-1.6.1-centos-7-rpm-with-transfers"
    timeout: 15m
#  - task: teardown
#    file: archivematica/ci/acceptance-tests/teardown-droplet.yml
#    params:
#      DROPLET_NAME: "archivematica-ci-tests-upgrade-pkg-centos-7"
#    timeout: 5m

- name: acceptance-tests-upgrade-ansible-ubuntu-16-04
  interruptible: true
  serial: true
  plan:
  - get: archivematica
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: archivematica/ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: ubuntu-16-04-x64
      SIZE: s-2vcpu-4gb
  - task: create-droplet-from-snapshot
    file: archivematica/ci/acceptance-tests/create-droplet-from-snapshot.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-16-04"
      SNAPSHOT_NAME: "am-1.6.1-ubuntu-xenial-ansible-with-transfers"
    timeout: 15m
  - ensure:
      task: teardown
      file: archivematica/ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-16-04"
      timeout: 5m
    do:
    - task: upgrade-archivematica
      file: upgrade-archivematica.yml
      timeout: 1h
    - task: install-default-user
      file: archivematica/ci/acceptance-tests/install-default-user.yml
      timeout: 10m

- name: acceptance-tests-upgrade-ansible-ubuntu-14-04
  interruptible: true
  serial: true
  plan:
  - get: archivematica
    trigger: true
    passed: [start-testing]
  - task: setup-tugboat
    file: archivematica/ci/acceptance-tests/setup-tugboat.yml
    params:
      ACCESS_TOKEN: ((digitalocean_api.access_token))
      SSH_USER: ((digitalocean_api.ssh_user))
      SSH_KEY: ((digitalocean_api.ssh_key))
      IMAGE: ubuntu-14-04-x64
      SIZE: s-2vcpu-4gb
  - task: create-droplet-from-snapshot
    file: archivematica/ci/acceptance-tests/create-droplet-from-snapshot.yml
    params:
      DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-14-04"
      SNAPSHOT_NAME: "am-1.6.1-ubuntu-trusty-ansible-with-transfers"
    timeout: 15m
  - ensure:
      task: teardown
      file: archivematica/ci/acceptance-tests/teardown-droplet.yml
      params:
        DROPLET_NAME: "archivematica-ci-tests-upgrade-ansible-ubuntu-14-04"
      timeout: 5m
    do:
    - task: upgrade-archivematica
      file: upgrade-archivematica.yml
      timeout: 1h
    - task: install-default-user
      file: archivematica/ci/acceptance-tests/install-default-user.yml
      timeout: 10m
