---
version: "2.1"

volumes:

  # Internal named volumes.
  # These are not accessible outside of the docker host and are maintained by
  # Docker.
  mysql_data:
  archivematica_storage_service_staging_data:

  # External named volumes.
  # These are intended to be accessible beyond the docker host (e.g. via NFS).
  # They use bind mounts to mount a specific "local" directory on the docker
  # host - the expectation being that these directories are actually mounted
  # filesystems from elsewhere.
  archivematica_pipeline_data:
    external:
      name: "am-pipeline-data"
  archivematica_storage_service_location_data:
    external:
      name: "ss-location-data"


services:

  mysql:
    image: "percona:5.6"
    user: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - "mysql_data:/var/lib/mysql"
    expose:
      - "3306"
    ports:
      - "62001:3306"

  redis:
    image: "redis:3.2-alpine"
    command: '--save "" --appendonly no'  # Persistency disabled
    user: "redis"
    expose:
      - "6379"
    ports:
      - "62003:6379"

  gearmand:
    image: "artefactual/gearmand:1.1.17-alpine"
    command: "--queue-type=redis --redis-server=redis --redis-port=6379"
    user: "gearman"
    expose:
      - "4730"
    ports:
      - "62004:4730"
    links:
      - "redis"

  fits:
    image: "artefactual/fits-ngserver:0.8.4"
    expose:
      - "2113"
    ports:
      - "62005:2113"
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"  # Read and write needed!

  clamavd:
    image: "artefactual/clamav:latest"
    expose:
      - "3310"
    ports:
      - "62006:3310"
    volumes:
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:ro"

  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/nginx/conf.d/archivematica.conf:/etc/nginx/conf.d/archivematica.conf:ro"
      - "./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    expose:
      - "80"
      - "8000"
    ports:
      - "62080:80"
      - "62081:8000"

  archivematica-mcp-server:
    build:
      context: "../src/archivematica/src"
      dockerfile: "MCPServer.Dockerfile"
    environment:
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.common"
      ARCHIVEMATICA_MCPSERVER_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_MCPSERVER_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_MCPSERVER_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_MCPARCHIVEMATICASERVER: "gearmand:4730"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-false}"
    volumes:
      - "../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../src/archivematica/src/dashboard/:/src/dashboard/"
      - "../src/archivematica/src/MCPServer/:/src/MCPServer/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "mysql"
      - "gearmand"

  archivematica-mcp-client:
    build:
      context: "../src/archivematica/src"
      dockerfile: "MCPClient.Dockerfile"
    environment:
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.common"
      NAILGUN_SERVER: "fits"
      NAILGUN_PORT: "2113"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_MCPARCHIVEMATICASERVER: "gearmand:4730"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER: "clamavd:3310"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-false}"
      ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT: "${AM_CAPTURE_CLIENT_SCRIPT_OUTPUT:-true}"
    volumes:
      - "../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../src/archivematica/src/dashboard/:/src/dashboard/"
      - "../src/archivematica/src/MCPClient/:/src/MCPClient/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    links:
      - "fits"
      - "clamavd"
      - "mysql"
      - "gearmand"
      - "archivematica-storage-service"

  archivematica-dashboard:
    build:
      context: "../src/archivematica/src"
      dockerfile: "dashboard.Dockerfile"
    environment:
      FORWARDED_ALLOW_IPS: "*"
      AM_GUNICORN_ACCESSLOG: "/dev/null"
      AM_GUNICORN_RELOAD: "true"
      AM_GUNICORN_RELOAD_ENGINE: "auto"
      DJANGO_SETTINGS_MODULE: "settings.local"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_GEARMAN_SERVER: "gearmand:4730"
      ARCHIVEMATICA_DASHBOARD_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_DASHBOARD_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_DASHBOARD_DASHBOARD_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-false}"
    volumes:
      - "../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "../src/archivematica/src/dashboard/:/src/dashboard/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
    expose:
      - "8000"
    links:
      - "mysql"
      - "gearmand"
      - "archivematica-storage-service"

  archivematica-storage-service:
    build:
      context: "../src/archivematica-storage-service"
    environment:
      FORWARDED_ALLOW_IPS: "*"
      SS_GUNICORN_ACCESSLOG: "/dev/null"
      SS_GUNICORN_RELOAD: "true"
      SS_GUNICORN_RELOAD_ENGINE: "auto"
      DJANGO_SETTINGS_MODULE: "storage_service.settings.local"
      SS_DB_URL: "mysql://archivematica:demo@mysql/SS"
      SS_GNUPG_HOME_PATH: "/src/"
    volumes:
      - "../src/archivematica-storage-service/:/src/"
      - "../src/archivematica-sampledata/:/home/archivematica/archivematica-sampledata/:ro"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
      - "archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"
      - "archivematica_storage_service_location_data:/home:rw"
    expose:
      - "8000"
    links:
      - "mysql"
