---
version: "2.1"

services:
  archivematica-acceptance-tests:
    build:
      context: "../src/archivematica-acceptance-tests"
      dockerfile: "Dockerfile"
    security_opt:
      - "seccomp:./etc/docker/seccomp/chrome.json"
    volumes:
      - "../src/archivematica-acceptance-tests:/home/archivematica/acceptance-tests:rw"
    links:
      - "nginx"
