{
 "title": "Archivematica",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Overview - $job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Last AIP stored",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(mcpclient_aips_stored_timestamp{job=~\"[[job]]\", instance=~\"[[instance]]\"}) * 1000"
      }
     ]
    },
    {
     "title": "Last Transfer started",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(mcpclient_transfer_started_timestamp{job=~\"[[job]]\", instance=~\"[[instance]]\"}) * 1000"
      }
     ]
    },
    {
     "title": "Last DIP stored",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(mcpclient_dips_stored_timestamp{job=~\"[[job]]\", instance=~\"[[instance]]\"}) * 1000"
      }
     ]
    },
    {
     "title": "In progress packages",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(mcpserver_active_packages{instance=~\"[[instance]]\"})"
      }
     ]
    },
    {
     "title": "AIPs stored",
     "type": "singlestat",
     "description": "Increase over the selected time range",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "round(sum(increase(mcpclient_aips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])))",
       "legendFormat": "AIPs stored"
      }
     ]
    },
    {
     "title": "Transfers started",
     "type": "singlestat",
     "description": "Increase over the selected time range",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "round(sum(increase(mcpclient_transfer_started_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])))"
      }
     ]
    },
    {
     "title": "DIPs stored",
     "type": "singlestat",
     "description": "Increase over the selected time range",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "round(sum(increase(mcpclient_dips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])))",
       "legendFormat": "AIPs stored"
      }
     ]
    },
    {
     "title": "Archivematica version",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "archivematica_version_info{job=~\"[[job]]\", instance=~\"[[instance]]\"}"
      }
     ]
    }
   ]
  },
  { "title": "Processing Details - $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "job" },
  {
   "title": "Transfers processed",
   "type": "graph",
   "description": "For all MCP clients, averaged over the selected time range, e.g. per hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "transfers / min" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(mcpclient_transfer_started_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])))",
     "legendFormat": "Transfers started"
    },
    {
     "expr": "sum by (job)(round(increase(mcpclient_transfer_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])))",
     "legendFormat": "Transfer errors"
    },
    {
     "expr": "sum by (job)(round(increase(mcpclient_transfer_completed_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])))",
     "legendFormat": "Transfers completed"
    }
   ]
  },
  {
   "title": "Packages stored",
   "type": "graph",
   "description": "By all MCPClients",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "packages / min" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(mcpclient_aips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])))",
     "legendFormat": "AIPs stored"
    },
    {
     "expr": "sum by (job)(round(increase(mcpclient_dips_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])))",
     "legendFormat": "DIPs stored "
    }
   ]
  },
  {
   "title": "Bytes processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes / min" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(increase(mcpclient_aip_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) or sum by (job)(increase(mcpclient_aip_size_bytes_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "AIPs"
    },
    {
     "expr": "sum by (job)(increase(mcpclient_dip_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) or sum by (job)(increase(mcpclient_dip_size_bytes_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "DIP bytes"
    },
    {
     "expr": "sum by (job)(increase(mcpclient_transfer_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "Transfer bytes"
    }
   ]
  },
  {
   "title": "Processing errors",
   "type": "graph",
   "description": "Across the pipeline, averaged over the time range given, e.g. per hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "errors / min" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(mcpclient_transfer_error_total{job=~\"[[job]]\", failure_type=\"fail\"}[1m])))",
     "legendFormat": "Transfer error - {{ job }}"
    },
    {
     "expr": "sum by (job)(round(increase(mcpclient_transfer_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\", failure_type=\"reject\"}[1m])))",
     "legendFormat": "Transfer rejected"
    },
    {
     "expr": "sum by (job)(round(increase(mcpclient_sip_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\", failure_type=\"fail\"}[1m])))",
     "legendFormat": "SIP error"
    },
    {
     "expr": "sum by (job)(round(increase(mcpclient_sip_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\", failure_type=\"reject\"}[1m])))",
     "legendFormat": "SIP rejected"
    }
   ]
  },
  {
   "title": "Files processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "files / min" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(round(increase(mcpclient_aip_files_stored_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))) or sum by (job)(round(increase(mcpclient_aip_files_stored_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])))",
     "legendFormat": "AIP files stored"
    },
    {
     "expr": "sum by (job)(round(increase(mcpclient_transfer_files_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])))",
     "legendFormat": "Transfer files ingested"
    }
   ]
  },
  {
   "title": "File Processing Analysis - $job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "job"
  },
  {
   "title": "Average number of files - AIPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(mcpclient_aip_files_stored_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]) / rate(mcpclient_aip_files_stored_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Average number of files - Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "files" }
   ],
   "targets": [
    {
     "expr": "sum by (transfer_type) (rate(mcpclient_transfer_files_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]) / rate(mcpclient_transfer_files_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{ transfer_type }}"
    }
   ]
  },
  {
   "title": "AIP number of files distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_aip_files_stored_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Transfer number of files distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_transfer_files_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average AIP size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(mcpclient_aip_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]) / rate(mcpclient_aip_size_bytes_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Average Transfer size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (transfer_type)(rate(mcpclient_transfer_size_bytes_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]) / rate(mcpclient_transfer_size_bytes_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{ transfer_type }}"
    }
   ]
  },
  {
   "title": "AIP size distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_aip_size_bytes_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Transfer size distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_transfer_size_bytes_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "File formats processed - Derivatives",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none", "label": "files / min" }
   ],
   "targets": [
    {
     "expr": "sum by (format_name,job)(round(increase(mcpclient_aip_files_stored_by_file_group_and_format_total{job=~\"[[job]]\", instance=~\"[[instance]]\", file_group=\"derivative\"}[1m])))",
     "legendFormat": "{{ format_name }}"
    }
   ]
  },
  {
   "title": "File formats processed - Originals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "none", "label": "files / min" }
   ],
   "targets": [
    {
     "expr": "sum by (job,format_name) (round(increase(mcpclient_aip_files_stored_by_file_group_and_format_total{job=~\"[[job]]\", instance=~\"[[instance]]\", file_group=\"original\"}[1m])))",
     "legendFormat": "{{ format_name }}"
    }
   ]
  },
  {
   "title": "File formats processed - Metadata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none", "label": "files / min" }
   ],
   "targets": [
    {
     "expr": "sum by (format_name,job)(round(increase(mcpclient_aip_files_stored_by_file_group_and_format_total{job=~\"[[job]]\", instance=~\"[[instance]]\", file_group=\"metadata\"}[1m])))",
     "legendFormat": "{{ format_name }}"
    }
   ]
  },
  {
   "title": "File modification year distribution",
   "type": "heatmap",
   "description": "original files only.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_aip_original_file_timestamps_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Performance Analysis - $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "repeat": "job" },
  {
   "title": "Average AIP processing time",
   "type": "graph",
   "description": "Average processing time over the past minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(rate(mcpclient_aip_processing_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]) / rate(mcpclient_aip_processing_seconds_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Average DIP processing time",
   "type": "graph",
   "description": "Average processing time over the past minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(rate(mcpclient_dip_processing_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]) / rate(mcpclient_dip_processing_seconds_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "AIP processing time distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_aip_processing_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "DIP processing time distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_dip_processing_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "reqs / min" }
   ],
   "targets": [
    {
     "expr": "increase(django_http_requests_total_by_method_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])",
     "legendFormat": "{{ method }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "HTTP errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum(rate(django_http_exceptions_total_by_type_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{ type }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total task execution time (MCPClient)",
   "type": "bargauge",
   "description": "Total time spent over the selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(mcpclient_task_execution_time_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])) by (script_name))",
     "legendFormat": "{{ script_name  }}"
    }
   ]
  },
  {
   "title": "Total task execution time (MCPServer)",
   "type": "bargauge",
   "description": "Total time spent over the selected time range. May vary from MCPClient as MCPserver is often waiting for client processing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(mcpserver_task_duration_seconds_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[$__range])) by (script_name))",
     "legendFormat": "{{ script_name  }}"
    }
   ]
  },
  { "title": "Developer Info - $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 }, "repeat": "job" },
  {
   "title": "Gearman pending jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 109 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mcpserver_gearman_pending_jobs{job=~\"[[job]]\", instance=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Gearman active jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 109 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mcpserver_gearman_active_jobs{job=~\"[[job]]\", instance=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Job queue length",
   "type": "singlestat",
   "description": "Length of the MCPServer job queue for *active* packages",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 109 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mcpserver_active_package_job_queue_length{job=~\"[[job]]\", instance=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "MCPServer task duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "sum(increase(mcpserver_task_duration_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "MCPServer tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "tasks / min" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mcpserver_task_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (job)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(increase(mcpserver_task_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (job)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "MCPClient task duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "sum(increase(mcpclient_task_execution_time_seconds_bucket{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "MCPClient jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "jobs / min" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mcpclient_job_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (instance)",
     "legendFormat": "Completed - {{instance}}"
    },
    {
     "expr": "sum(increase(mcpclient_job_error_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (instance)",
     "legendFormat": "Errored - {{instance}}"
    }
   ]
  },
  {
   "title": "Average HTTP request time by view",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=~\"[[job]]\", instance=~\"[[instance]]\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=~\"[[job]]\", instance=~\"[[instance]]\"}[5m])",
     "legendFormat": "{{ method}}: {{ view}}"
    }
   ]
  },
  {
   "title": "Django model updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short", "label": "saves / min" }
   ],
   "targets": [
    {
     "expr": "sum(increase(django_model_save_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])) by (job,model)",
     "legendFormat": "{{job}} - {{ model }}"
    }
   ]
  },
  {
   "title": "CPU seconds by python process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{job=~\"[[job]]\", instance=~\"[[instance]]\"}[5m])",
     "legendFormat": "{{ job }} - {{ instance }}"
    }
   ]
  }
 ]
}